version: "3.8"
services:
  kholles_server:
    image: kholles_server
    container_name: kholles_server
    volumes:
      - ./content:/app/content
    ports:
      - "3680:3680"
    restart: "unless-stopped"
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: "3680"
      FS_LISTEN_PATH: "content"
    env_file:
      - .env
